version: 2
jobs:     
  test:
    working_directory: ~/btrz-mongo-service
    docker:
      - image: circleci/node:8.12.0-jessie
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install --no-package-lock
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: ./test-results/cobertura-coverage.xml
          prefix: cobertura-coverage
      - store_artifacts:
          path: ./test-results/lcov-report
          prefix: lcov-1coverage

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only: master
