version: 2
jobs:
  publish:
    working_directory: ~/btrz-mongo-service
    docker:
      - image: circleci/node:8.12.0-jessie
    steps:
      - checkout
      - run:
          name: Install npm
          command: npm install --no-package-lock
      - run:
          name: Run lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: ./test-results/cobertura-coverage.xml
          prefix: cobertura-coverage
      - store_artifacts:
          path: ./test-results/lcov-report
          prefix: lcov-1coverage
      - run:
          name: Publish to npm
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            npm run publish


workflows:
  version: 2
  publish:
    jobs:
      - publish:
          filters:
            branches:
              only: master
